core/models/User.php
<?php
/**
 * @link http://simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\helpers\ArrayHelper;
use app\components\Util;

class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_BANNED = 0;
    const STATUS_INACTIVE = 8;
    const STATUS_ADMIN_VERIFY = 9;
    const STATUS_ACTIVE = 10;
    const ROLE_MEMBER = 0;
    const ROLE_ADMIN = 10;
    const USERNAME_PATTERN = '/^[a-zA-Z0-9\x{4e00}-\x{9fa5}]*$/u';
    const USER_MENTION_PATTERN = '/\B\@([a-zA-Z0-9\x{4e00}-\x{9fa5}]{4,20})/u';

    public static $statusOptions = [
        0 => '被屏蔽用户',
        8 => '待激活用户',
        9 => '待管理员验证用户',
        10 => '正常用户',
    ];

    public static $roleOptions = [
        0 => '用户组',
        10 => '管理员',
    ];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['avatar', 'safe'],
//            ['role', 'default', 'value' => self::ROLE_MEMBER],
//            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'integer', 'max'=>self::STATUS_ACTIVE, 'min'=>self::STATUS_BANNED],
        ];
    }

    public function getNoticeCount()
    {
        return Notice::find()->where(['status'=>0, 'target_id' => $this->id])->count('id');
    }

    public function getSystemNoticeCount()
    {
        return Notice::find()->where(['status'=>0, 'target_id' => $this->id])->andWhere(['<>', 'type', Notice::TYPE_MSG])->count('id');
    }

    public function getSmsCount()
    {
        return Notice::find()->where(['status'=>0, 'target_id' => $this->id, 'type'=>Notice::TYPE_MSG])->count('id');
    }

    public function getNotices()
    {
        return $this->hasMany(Notice::className(), ['target_id' => 'id'])
            ->where(['status'=>0])->orderBy(['updated_at'=>SORT_DESC]);
    }

    public function getAuths()
    {
        return $this->hasMany(Auth::className(), ['user_id' => 'id'])
            ->orderBy(['id'=>SORT_DESC]);
    }

    public function getTopics()
    {
        return $this->hasMany(Topic::className(), ['user_id' => 'id'])
            ->select(['id', 'node_id', 'user_id', 'reply_id', 'title', 'comment_count', 'replied_at'])
            ->limit(10)->orderBy(['id'=>SORT_DESC]);
    }

    public function getComments()
    {
        return $this->hasMany(Comment::className(), ['user_id' => 'id'])
            ->select(['id', 'user_id', 'topic_id', 'created_at', 'invisible', 'content'])
            ->limit(10)->orderBy(['id'=>SORT_DESC]);
    }

    public function getUserInfo()
    {
        return $this->hasOne(UserInfo::className(), ['user_id' => 'id']);
    }

    public function getLastAction($action = History::ACTION_ADD_TOPIC)
    {
        return $this->hasOne(History::className(), ['user_id' => 'id'])
                ->select(['action_time', 'action', 'target', 'ext'])
                ->where(['action'=>$action])
                ->orderBy(['action_time'=>SORT_DESC])->limit(1);
    }

    public function getAction($where)
    {
        return $this->hasOne(History::className(), ['user_id' => 'id'])
                ->select(['action_time', 'action', 'target', 'ext'])
                ->where($where)->limit(1);
    }

    public function isAdmin()
    {
        return (intval($this->role) === self::ROLE_ADMIN);
    }

    public function isActive()
    {
        return (intval($this->status) >= self::STATUS_ACTIVE);
    }

    public function isInactive()
    {
        return (intval($this->status) === self::STATUS_INACTIVE || intval($this->status) === self::STATUS_ADMIN_VERIFY);
    }

    public function isWatingActivation()
    {
        return (intval($this->status) === self::STATUS_INACTIVE);
    }

    public function isWatingVerification()
    {
        return (intval($this->status) === self::STATUS_ADMIN_VERIFY);
    }

    public function isAuthor($user_id)
    {
        return ($this->id == $user_id);
    }

    public function isExpired($created_at)
    {
        return ( time() > $created_at + intval(Yii::$app->params['settings']['edit_space'])*60 );
    }

    public function canEdit($model, $status=0)
    {
        return ( self::isAdmin() || $status == 0 && self::isActive()
                 && self::isAuthor($model['user_id'])
                 && !self::isExpired($model['created_at'])
                );
    }

    public function canPost($action=History::ACTION_ADD_TOPIC)
    {
        if ( self::isAdmin() ) {
            return true;
        } else if ( !self::isActive() ) {
            return false;
        }
        $key = 'settings.'. ($action===History::ACTION_ADD_TOPIC ? 'topic_space' : 'comment_space');
        $postSpace = ArrayHelper::getValue(Yii::$app->params, $key, 0);
        $lastTime = ArrayHelper::getValue(self::getLastAction($action)->asArray()->one(), 'action_time', 0);
        return (  time() > intval($lastTime) + intval($postSpace) );
    }

    public function canReply($model)
    {
        return ( intval($model['comment_closed']) === 0 && self::isActive() );
    }

    public function canUpload($settings)
    {
        if ( $settings['upload_file'] === 'disable' ) {
            return false;
        }
        if ( self::isAdmin() ) {
            return true;
        } else if ( !self::isActive() ) {
            return false;
        }

        return (
            $this->created_at+intval($settings['upload_file_regday'])*24*3600 < time()
            && $this->userInfo->topic_count >= intval($settings['upload_file_topicnum'])
        );
    }

    public function hasReplied($topicId)
    {
        return Comment::find()->where(['topic_id'=>$topicId, 'user_id'=>$this->id])->count();
    }

    public function getStatus()
    {
        return self::$statusOptions[$this->status];
    }

    public function getRole()
    {
        return self::$roleOptions[$this->role];
    }

    public static function getCost($action)
    {
        $costs = [
            'reg' => 1000,  //注册
            'addTopic' => -20,  //发表主题
            'addComment' => -5, //发表回复
            'commented' => 5,   //被回复,不能为负数
            'sendMsg' => -5,    //发送短消息
            'buyInviteCode' => -50, //购买邀请码
            'signin_10days' => 200, //连续签到10天奖励
            'signin' => function() {return rand(10, 50);},  //签到奖励10-50的随机数
            'thanks' => -20, //感谢：自己扣分，对方加分
        ];
        if ($action === 'signin') {
            return $costs[$action]();
        } else {
            return $costs[$action];
        }
    }

    public function checkActionCost($action)
    {
        return ($this->score + static::getCost($action))>=0;
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
//        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
        return static::find()->where(['id' => $id])
                ->andWhere(['>=', 'status', self::STATUS_INACTIVE])
                ->one();
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
//        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
        return static::find()->where(['username' => $username])
                ->andWhere(['>=', 'status', self::STATUS_INACTIVE])
                ->one();
    }

    public static function findByEmail($email)
    {
        return static::find()->where(['email' => $email])
                ->andWhere(['>=', 'status', self::STATUS_INACTIVE])
                ->one();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->getSecurity()->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->getSecurity()->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Util::generateRandomString();
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($insert === true) {
            $userIP = sprintf("%u", ip2long(Yii::$app->getRequest()->getUserIP()));
            (new UserInfo([
                'user_id' => $this->id,
                'reg_ip' => $userIP,
                'last_login_at'=>$this->created_at,
                'last_login_ip'=>$userIP,
            ]))->save(false);
            Siteinfo::updateCounterInfo('addUser');
/*          if ( intval(Yii::$app->params['settings']['email_verify']) === 1) {
                Token::sendActivateMail($this);
            }*/

core/controllers/UserController.php
<?php
/**
 * @link http://simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

namespace app\controllers;

use Yii;
use yii\data\Pagination;
use yii\web\NotFoundHttpException;
use app\models\User;
use app\models\Topic;
use app\models\Comment;

class UserController extends AppController
{
    public function actionView($username)
    {
        $req = Yii::$app->getRequest();
        if ($req->getIsAjax()) {
            $this->layout = false;
            $model = $this->findUserModel($username, ['userInfo']);
            return $this->render('ajaxView', [
                 'user' => $model,
            ]);
        } else {
            $model = $this->findUserModel($username, ['userInfo', 'topics.node', 'topics.lastReply', 'comments.topic.author']);
            return $this->render('view', [
                 'user' => $model,
            ]);
        }
    }

    public function actionTopics($username)
    {
        $user = $this->findUserModel($username, ['userInfo']);
        $pages = new Pagination(['totalCount' => $user['userInfo']['topic_count'], 'pageSize' => $this->settings['list_pagesize'], 'pageParam'=>'p']);
        $topics = Topic::find()->select('id')->where(['user_id' => $user['id']])
            ->orderBy(['id'=>SORT_DESC])->offset($pages->offset)
            ->with(['topic.node', 'topic.lastReply'])
            ->limit($pages->limit)
            ->asArray()
            ->all();

        return $this->render('topics', [
             'user' => $user,
             'topics' => $topics,
             'pages' => $pages,
        ]);
    }

    public function actionComments($username)
    {
        $user = $this->findUserModel($username, ['userInfo']);
        $pages = new Pagination(['totalCount' => $user['userInfo']['comment_count'], 'pageSize' => $this->settings['list_pagesize'], 'pageParam'=>'p']);
        $comments = Comment::find()->select(['id', 'created_at', 'topic_id', 'content', 'invisible'])->where(['user_id' => $user['id']])
            ->orderBy(['id'=>SORT_DESC])->offset($pages->offset)
            ->with(['topic.author'])
            ->limit($pages->limit)
            ->asArray()
            ->all();

        return $this->render('comments', [
             'user' => $user,
             'comments' => $comments,
             'pages' => $pages,
        ]);
    }

    protected function findUserModel($username, $with=null)
    {
        $model = User::find()->select(['id', 'created_at', 'status', 'username', 'avatar', 'score', 'comment'])->where(['username'=>$username]);
        if ( !empty($with) ) {
            $model = $model->with($with);
        }
        $model = $model->asArray()->one();

        if ($model !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('未找到['.$username.']的用户');
        }
    }

}

core/views/user/ajaxView.php
<?php
/**
 * @link http://simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use app\models\Favorite;
use app\components\SfHtml;

$this->title = Html::encode($user['username']);
$settings = Yii::$app->params['settings'];

$fomatter = Yii::$app->getFormatter();
$isGuest = Yii::$app->getUser()->getIsGuest();
if (!$isGuest) {
    $me = Yii::$app->getUser()->getIdentity();
}

$userOp = [];
if (!$isGuest && $me->isActive() && $me->id != $user['id']) {
    if (Favorite::checkFollow($me->id, Favorite::TYPE_USER, $user['id'])) {
        $favorIcon = 'fa-star';
        $favorName = '取消关注';
        $favorParams = 'unfavorite';
    } else {
        $favorIcon = 'fa-star-o';
        $favorName = '关注 Ta';
        $favorParams = 'favorite';
    }
    $userOp['follow'] = Html::a('<i class="fa '.$favorIcon.' fa-lg aria-hidden="true""></i><span class="favorite-name">'.$favorName.'</span>', null, ['class'=>'btn btn-xs btn-default favorite', 'title'=>$favorName, 'href' => 'javascript:void(0);', 'params'=> $favorParams.' user '. $user['id']]);
    $userOp['sms'] = Html::a('<i class="fa fa-envelope-o fa-lg" aria-hidden="true"></i><span class="favorite-name">私信 Ta</span>', ['service/sms', 'to'=>Html::encode($user['username'])], ['class'=>'btn btn-xs btn-default']);
}

?>

<ul class="list-group user-card">
  <li class="list-group-item text-center user-card-heading" style="background-image:url(<?php echo Yii::getAlias('@web/'.str_replace('{size}', 'cover_m', $user['userInfo']['cover']));?>)">
    <?php echo SfHtml::uImg($user, 'normal'); ?>
    <div style="margin-top:2px;">
<?php
    echo '<span class="username">', $this->title, '</span><span class="group small">', SfHtml::uGroup($user['score']);
    if ( !empty($user['userInfo']['website']) ) {
        echo ' ', Html::a('<i class="fa fa-home fa-lg" aria-hidden="true"></i>', $user['userInfo']['website'], ['target'=>'_blank']);
    }
?>
    </div>
    <div class="small time">
<?php
    echo 'from ', Yii::$app->getFormatter()->asDateTime($user['created_at'], 'y-MM-dd');
?>
    </div>
    <?php if( !empty($user['userInfo']['about']) ) : ?>
    <div class="small profile">
    <?php 
        echo '简介：'. Html::encode(mb_strlen($user['userInfo']['about'])>19?mb_substr($user['userInfo']['about'], 0, 16).'...':$user['userInfo']['about']);
    ?>
    </div>
    <?php endif ?>
  </li>
  <li class="list-group-item text-center small">
      <p><strong>关注 <?php echo $user['userInfo']['favorite_user_count'] ?></strong> | 
      <strong>粉丝 <span class="favorite-num"><?php echo $user['userInfo']['favorite_count']; ?></span></strong> |
      <strong>主题 <?php echo $user['userInfo']['topic_count']; ?></strong> |
      <strong>回复 <?php echo $user['userInfo']['comment_count']; ?></strong></p>
      <?php echo implode(' ', $userOp); ?>
  </li>
</ul>

core/views/user/balance.php
<?php
/**
 * @link http://simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\widgets\LinkPager;
use app\models\History;
use app\lib\Util;

$this->title = '账户余额';
$formatter = Yii::$app->getFormatter();
$me = Yii::$app->getUser()->getIdentity();

$types = [
    History::ACTION_REG => '注册帐号',
    History::ACTION_ADD_TOPIC => '发表主题',
    History::ACTION_ADD_COMMENT => '回复主题',
    History::ACTION_COMMENTED => '主题回复收益',
    History::ACTION_ORIGINAL_SCORE => '初始积分',
    History::ACTION_SIGNIN => '每日登录奖励',
    History::ACTION_SIGNIN_10DAYS => '连续登录奖励',
    History::ACTION_INVITE_CODE => '购买邀请码',
];

function getComment($action, $ext) {
    $str = '';
    if( $action == History::ACTION_ADD_TOPIC ) {
        $str = '发表了主题 › ' . Html::a(Html::encode($ext['title']), ['topic/view', 'id'=>$ext['topic_id']]);
    } else if( $action == History::ACTION_ADD_COMMENT ) {
        $str = '回复了主题 › ' . Html::a(Html::encode($ext['title']), ['topic/view', 'id'=>$ext['topic_id']]);
    } else if( $action == History::ACTION_ORIGINAL_SCORE ) {
        $str = '获得初始积分 ' . $ext['cost'];
    } else if( $action == History::ACTION_COMMENTED ) {
        $str = '收到 ' . Html::a(Html::encode($ext['commented_by']), ['user/view', 'username'=>$ext['commented_by']]) . ' 的回复 › '. Html::a(Html::encode($ext['title']), ['topic/view', 'id'=>$ext['topic_id']]);
    } else if( $action == History::ACTION_SIGNIN ) {
        $str = '每日登录奖励 ' . $ext['cost'] . ' 积分';
    } else if( $action == History::ACTION_SIGNIN_10DAYS ) {
        $str = '连续登录每 10 天奖励 ' . $ext['cost'] . ' 积分';
    } else if( $action == History::ACTION_INVITE_CODE ) {
        $str = '购买了 ' . $ext['amount'] . ' 枚邀请码';
    } else if( $action == History::ACTION_REG ) {
        $str = '注册帐号奖励 ' . $ext['cost'] . ' 积分';
    }
    return $str;
}
function getCost($cost) {
    $cost = intval($cost);
    $color = $cost>0?'blue':'red';
    return '<span class="' . $color . '">' . $cost . '</span>';
}

?>

<div class="row">
<div class="col-md-8 sf-left">

<ul class="list-group sf-box">
    <li class="list-group-item">
    <?php echo Html::a('首页', ['topic/index']), '&nbsp;/&nbsp;', $this->title; ?>
    </li>
    <li class="list-group-item">
        <h4>当前账户余额： <?php echo Util::getScore($me->score); ?></h4>
    </li>
    <li class="list-group-item">
    <table class="table table-condensed table-bordered small">
      <thead>
        <tr>
          <th>类型/时间</th>
          <th>数额</th>
          <th>余额</th>
          <th>描述</th>
        </tr>
      </thead>
      <tbody>
<?php
foreach($records as $record) {
    $ext = unserialize($record['ext']);
    echo '<tr>',
            '<td width="120">', $types[$record['action']], '<br />', $formatter->asDateTime($record['action_time'], 'y-MM-dd HH:mm'), '</td>',
            '<td width="50" class="text-right"><strong>', getCost($ext['cost']), '</strong></td>',
            '<td width="60" class="text-right">', $ext['score'], '</td>',
            '<td width="auto">', getComment($record['action'], $ext), '</td>',
         '</tr>';
}
?>
      </tbody>
    </table>
    </li>
    <li class="list-group-item item-pagination">
    <?php
    echo LinkPager::widget([
        'pagination' => $pages,
    ]);
    ?>
    </li>

</ul>
</div>

<div class="col-md-4 sf-right">
<?php echo $this->render('@app/views/common/_right'); ?>
</div>

</div>

core/views/user/buyInviteCode.php
<?php
/**
 * @link http://simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = '购买优惠码';
?>

<div class="row">
<!-- sf-left start -->
<div class="col-md-8 sf-left">

<div class="panel panel-default sf-box">
    <div class="panel-heading">
        <?php echo Html::a('首页', ['topic/index']), '&nbsp;/&nbsp;', $this->title; ?>
    </div>
    <div class="panel-body sf-box-form">
        <?php $form = ActiveForm::begin([
            'layout' => 'horizontal',
            'id' => 'form-buy-invite-codes'
        ]); ?>
            <?php echo $form->field($model, 'amount')->textInput(['maxlength'=>3]); ?>
            <?php echo $form->field($model, 'password')->passwordInput(['maxlength'=>20]); ?>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                <?php echo Html::submitButton('确定', ['class' => 'btn btn-primary']); ?>
                </div>
            </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

</div>
<!-- sf-left end -->

<!-- sf-right start -->
<div class="col-md-4 sf-right">
<?php echo $this->render('@app/views/common/_right'); ?>
</div>
<!-- sf-right end -->

</div>

core/views/user/comments.php
<?php
/**
 * @link http://simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\bootstrap\Alert;
use app\components\SfHtml;
use app\models\User;

$this->title = Html::encode($user['username']).'的全部回复';
$formatter = Yii::$app->getFormatter();
$settings = Yii::$app->params['settings'];

//$editor = new \app\lib\Editor(['editor'=>$settings['editor']]);
$editorClass = '\app\plugins\\'. $settings['editor']. '\\'. $settings['editor'];
$editor = new $editorClass();

$isGuest = Yii::$app->getUser()->getIsGuest();
if(!$isGuest) {
    $me = Yii::$app->getUser()->getIdentity();
}
$whiteWrapClass = $settings['editor']=='SmdEditor'?'white-wrap':'';

?>

<div class="row">
<div class="col-md-8 sf-left">

<ul class="list-group sf-box">
    <li class="list-group-item">
        <?php echo Html::a('首页', ['topic/index']), '&nbsp;›&nbsp;', SfHtml::uLink($user['username']), '&nbsp;›&nbsp;全部回帖'; ?>
    </li>
<?php
foreach($comments as $comment):
?>
    <li class="list-group-item gray small list-group-item-info">
        <p class='fr'><?php echo $formatter->asRelativeTime($comment['created_at']); ?></p>
        回复了 <?php echo SfHtml::uLink($comment['topic']['author']['username']); ?> 创建的主题 › <?php echo Html::a(Html::encode($comment['topic']['title']), ['topic/view', 'id'=>$comment['topic_id']]); ?>
    </li>
    <li class="list-group-item word-wrap <?php echo $whiteWrapClass; ?>">
    <?php
        $commentShow = true;
        if ( $comment['invisible'] == 1 || $user['status'] == User::STATUS_BANNED ) {
            echo Alert::widget([
                'options' => ['class' => 'alert-warning'],
                'closeButton'=>false,
                'body' => '此回复已被屏蔽',
            ]);
            $commentShow = false;
        }
        if( $commentShow === true || !$isGuest && $me->isAdmin() ) {
            echo $editor->parse($comment['content']);
        }
    ?>
    </li>
<?php endforeach; ?>
    <li class="list-group-item item-pagination">
    <?php
    echo LinkPager::widget([
        'pagination' => $pages,
        'maxButtonCount'=>5,
    ]);
    ?>
    </li>
</ul>

</div>

<div class="col-md-4 sf-right">
<?php echo $this->render('@app/views/common/_right'); ?>
</div>

</div>

core/views/user/inviteCodes.php
<?php
/**
 * @link http://simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\widgets\LinkPager;
use app\models\History;
use app\models\Token;
use app\lib\Util;

$this->title = '我的邀请码';
$formatter = Yii::$app->getFormatter();
$me = Yii::$app->getUser()->getIdentity();

?>

<div class="row">
<div class="col-md-8 sf-left">

<ul class="list-group sf-box">
    <li class="list-group-item">
    <?php echo Html::a('首页', ['topic/index']), '&nbsp;/&nbsp;', $this->title; ?>
    </li>
    <li class="list-group-item">
        <h4>当前账户余额： <?php echo Util::getScore($me->score); ?></h4>
    </li>
    <li class="list-group-item">
    <table class="table table-condensed table-bordered">
      <thead>
        <tr>
          <th>邀请码</th>
          <th>有效期</th>
          <th>状态</th>
        </tr>
      </thead>
      <tbody>
<?php
foreach($records as $record) {
//    $ext = unserialize($record['ext']);
    echo '<tr', ($record['status']==0)?'':' class="active"', '>',
            '<td>', ($record['status']==0)?$record['token']:'<del>'.$record['token'].'</del>', '</td>',
            '<td>', ($record['expires'] == 0)?'永久有效':$formatter->asDateTime($record['expires'], 'y-MM-dd HH:mm:ss'), '</td>',
            '<td>', ($record['status']==0)?'未使用':'已使用', '</td>',
         '</tr>';
}
?>
      </tbody>
    </table>
    </li>
    <li class="list-group-item item-pagination">
    <?php
    echo LinkPager::widget([
        'pagination' => $pages,
    ]);
    ?>
    </li>

</ul>
</div>

<div class="col-md-4 sf-right">
<?php echo $this->render('@app/views/common/_right'); ?>
</div>

</div>

core/views/user/signin.php
<?php
/**
 * @link http://simpleforum.org/
 * @copyright Copyright (c) 2016 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\bootstrap\Alert;

$this->title = '每日签到';
?>

<div class="row">
<!-- sf-left start -->
<div class="col-md-8 sf-left">

<div class="panel panel-default sf-box">
    <div class="panel-heading">
        <?php echo Html::a('首页', ['topic/index']), '&nbsp;/&nbsp;', $this->title; ?>
    </div>
    <div class="panel-body">
        <?php echo Html::a('<i class="fa fa-gift" aria-hidden="true"></i>请点击签到', Yii::$app->getRequest()->url, [
            'title' => '签到',
            'class' => 'btn btn-primary',
            'data' => [
                'method' => 'post',
            ]]);
        ?>
    </div>
</div>

</div>
<!-- sf-left end -->

<!-- sf-right start -->
<div class="col-md-4 sf-right">
<?php echo $this->render('@app/views/common/_right'); ?>
</div>
<!-- sf-right end -->

</div>